### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dmartin015** [Wertzui123/Netherite#1]
When I press to put on the armor directly the armor is doubled

**Comment by Wertzui123** [comment]
You are probably using another plugin that causes this. Please look up any plugins that add instant armor equipping by right-clicking because this is already implemented in PocketMine itself and such plugins mess things up.

**Comment by UnEnanoMas** [comment]
Look at the piggy custom enchants configuration

**Comment by Wertzui123** [comment]
Did you figure out the root of the problem?

**Comment by Wertzui123** [comment]
Please reopen the issue if the problem still occurs for you.
