### ISSUE TITLE
Items don't lose durability and piggy ce support

### ISSUE THREAD

**Issue by BrahmjotSingh0** [Wertzui123/Netherite#2]
Hey ,
We can't add piggy custom enchants to netherite plugin.
It would be gud if u ass support so we can add piggy custom enchants to netherite armor and tools.
Also armor and tools doesn't loose durability.
Hope it fixed ty ;)

**Comment by Wertzui123** [comment]
I don't know how Piggy CE works internally, but I think it's because the netherite items in this plugin are not the same kind of tool as the other tools are. I don't think I can solve this, maybe DaPigGuy will add support for this plugin in Piggy CE, but that would be quite inconvenient.

**Comment by Wertzui123** [comment]
> Also armor and tools doesn't loose durability.

Forgot about this; I don't know what's the problem here, I'll look at this later.

**Comment by BrahmjotSingh0** [comment]
Armor not loosing durability fixed after i reset the plugin once also okay if ce can't be supported i will try to ask dapigguy about it ty!

**Comment by Wertzui123** [comment]
Nice!

**Comment by Wertzui123** [comment]
PiggyCE should now work together with Netherite.
