### ISSUE TITLE
Unable to accept Altay

### ISSUE THREAD

**Issue by Cher0325** [Wertzui123/Netherite#6]
14:32:19 Server|INFO > Enabling Netherite v1.2.1

Fatal error: Class Wertzui123\Netherite\item\armor\NetheriteHelmet contains 1 ab implement the remaining methods (pocketmine\item\Armor::getArmorSlot) in phar:/e/item/armor/NetheriteHelmet.php on line 25
14:32:19 Server|EMERGENCY > An unrecoverable error has occurred and the server h14:32:19 Server|EMERGENCY > Please upload the "/root/DN/crashdumps/Thu_Jul_15-14t the link to the Bug Reporting page. Give as much info as you can.

**Comment by Wertzui123** [comment]
Hi, what version of PocketMine are you using?

**Comment by Wertzui123** [comment]
Oh, yea, I should read the title, I am sorry.
Looks like this plugin does not work on Altay.
