### ISSUE TITLE
Can’t combo and bugs other armors and normal players

### ISSUE THREAD

**Issue by Awsomegamer322** [Wertzui123/Netherite#7]
You can't combo anyone so it's harder to pvp

**Comment by Wertzui123** [comment]
How do you even combo someone?

**Comment by Awsomegamer322** [comment]
when you keep on hitting the  player and there in the air they cant hit you

**Comment by Wertzui123** [comment]
Ah, thanks.
And that does not work when the player you are trying to combo has Netherite armor?

**Comment by Awsomegamer322** [comment]
correct because you can do it with diamond armor

**Comment by Wertzui123** [comment]
I will look at it.

**Comment by Awsomegamer322** [comment]
ok

**Comment by DRAGKILLS** [comment]
its netherite u cant combo someone or if u want u can use the player motion

**Comment by MrBlasyMSK** [comment]
It is not a bug, Netherite armor by part has +2 resistance to knockdown, that makes you can not execute combos in pvp, but that was designed by Mojang, is not a bug of the plugin.

@Wertzui123 removes the bug tag and closes the issue

**Comment by Wertzui123** [comment]
Yeah, that may have caused the confusion.
