### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by supercrafter333** [Wertzui123/Netherite#8]
The plugin doesn't add netherit in PM4. I can't get a netherit tool in in my inventory and or per command.
![image](https://user-images.githubusercontent.com/53967726/144727149-2c7cd155-f049-49a0-9c5d-d4e8fe6a9a7d.png)

**Comment by Wertzui123** [comment]
As already pointed out by @jasonwynn10, it does not work with the `/give` command yet.
Besides that, it does work for me and others though.

Try to test it on a clean server without any other plugins.

**Comment by supercrafter333** [comment]
Jo, ich hab nen CustomItem falsch registriert und das feierte PM4 nicht so xD

Funktioniert jetzt im Inventar, danke dir :)
